version: '{build}'
image: Visual Studio 2019
init:
- git config --global core.autocrlf true
configuration:
- Debug
- Release
before_build:
- ps: .\init.ps1 -NoRestore
- nuget restore
skip_tags: true
build:
  project: StyleCopAnalyzers.sln
  verbosity: minimal
test_script:
- .\StyleCop.Analyzers\StyleCop.Analyzers.Status.Generator\bin\%Configuration%\net46\StyleCop.Analyzers.Status.Generator.exe .\StyleCopAnalyzers.sln > StyleCop.Analyzers.Status.json
cache:
  - packages -> **\packages.config
  - C:\Users\appveyor\.nuget\packages -> appveyor.yml

artifacts:
- path: '**\*.*'
